---
- name: Check if directories have contents
  hosts: all
  become: yes
  tasks:
    - name: Check directory contents
      find:
        paths: "{{ item }}"
        file_type: any
      register: dir_contents
      loop:
        - /mnt/AppData
        - /mnt/Archive
        - /mnt/Downloads
        - /mnt/Media
        - /mnt/VS-Code
    - name: Fail if directory is empty
      fail:
        msg: "Directory {{ item.item }} is empty"
      loop: "{{ dir_contents.results }}"
      when: item.files|length == 0